import React from 'react';
import { FiArrowLeft } from 'react-icons/fi';
import { Link } from 'react-router-dom';

const PrivacyPolicy = () => {
    return (
        <div style={{
            maxWidth: '800px',
            margin: '0 auto',
            padding: '40px 20px',
            color: 'var(--text)',
            fontFamily: 'inherit',
            lineHeight: '1.6'
        }}>
            <Link to="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', color: 'var(--accent)', textDecoration: 'none', marginBottom: '32px', fontWeight: 'bold' }}>
                <FiArrowLeft /> Back to App
            </Link>

            <h1 style={{ fontSize: '2.5rem', marginBottom: '8px', color: 'var(--text)' }}>Privacy Policy</h1>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '32px' }}>Last updated: {new Date().toLocaleDateString()}</p>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ fontSize: '1.5rem', marginBottom: '16px', color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>1. Introduction</h2>
                <p>Welcome to LevelUp Study Planner. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our application. Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the application.</p>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ fontSize: '1.5rem', marginBottom: '16px', color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>2. Information We Collect</h2>
                <p style={{ marginBottom: '12px' }}>We may collect information about you in a variety of ways. The information we may collect via the Application includes:</p>
                <ul style={{ paddingLeft: '24px', listStyleType: 'disc' }}>
                    <li style={{ marginBottom: '8px' }}><strong>Personal Data:</strong> Personally identifiable information, such as your name and email address, that you voluntarily give to us when you register with the Application using Google OAuth.</li>
                    <li style={{ marginBottom: '8px' }}><strong>Application Data:</strong> Data generated by your use of the application, including study subjects, topics, tasks, pomodoro timer history, and gamification statistics (XP, level). This data is securely stored in Google Firebase Firestore.</li>
                    <li style={{ marginBottom: '8px' }}><strong>Google Calendar Data:</strong> If you choose to sync your tasks, we request permission to manage your Google Calendar. We only create events on your behalf and do not read, delete, or modify existing events unrelated to this application.</li>
                </ul>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ fontSize: '1.5rem', marginBottom: '16px', color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>3. Use of Your Information</h2>
                <p style={{ marginBottom: '12px' }}>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Application to:</p>
                <ul style={{ paddingLeft: '24px', listStyleType: 'disc' }}>
                    <li style={{ marginBottom: '8px' }}>Create and manage your account.</li>
                    <li style={{ marginBottom: '8px' }}>Provide the core functionality of the planner (tracking tasks, study groups, pomodoro history).</li>
                    <li style={{ marginBottom: '8px' }}>Sync your study schedule to your Google Calendar (only if explicitly authorized).</li>
                    <li style={{ marginBottom: '8px' }}>Generate personalized AI courses using Google Gemini.</li>
                </ul>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ fontSize: '1.5rem', marginBottom: '16px', color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>4. Disclosure of Your Information</h2>
                <p>We do not sell, trade, or rent your personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates, and advertisers.</p>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ fontSize: '1.5rem', marginBottom: '16px', color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>5. Third-Party Services</h2>
                <p style={{ marginBottom: '12px' }}>Our application utilizes the following third-party services that may collect information used to identify you:</p>
                <ul style={{ paddingLeft: '24px', listStyleType: 'disc' }}>
                    <li style={{ marginBottom: '8px' }}><strong>Google Play Services:</strong> Used for authentication and database housing via Firebase.</li>
                    <li style={{ marginBottom: '8px' }}><strong>Google Calendar API:</strong> Used strictly for adding study tasks to your personal calendar.</li>
                    <li style={{ marginBottom: '8px' }}><strong>Google Gemini API:</strong> Used to generate course structures based on your text prompts. No personally identifiable information is sent to the AI.</li>
                </ul>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ fontSize: '1.5rem', marginBottom: '16px', color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>6. Security of Your Information</h2>
                <p>We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.</p>
            </section>

            <section style={{ marginBottom: '32px' }}>
                <h2 style={{ fontSize: '1.5rem', marginBottom: '16px', color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>7. Contact Us</h2>
                <p>If you have questions or comments about this Privacy Policy, please contact the developer at <strong>rayhaanlibish@gmail.com</strong>.</p>
            </section>
        </div>
    );
};

export default PrivacyPolicy;
